package me.phoenixra.atumodcore.api.input;

public enum InputType {
    KEYBOARD_KEY,
    KEYBOARD_LEFT_CTRL,
    KEYBOARD_RIGHT_CTRL,
    KEYBOARD_SHIFT,
    KEYBOARD_LEFT_ALT,
    KEYBOARD_RIGHT_ALT,
    KEYBOARD_ENTER,
    KEYBOARD_SPACE,
    KEYBOARD_BACKSPACE,
    KEYBOARD_TAB,
    KEYBOARD_ESCAPE,

    MOUSE_RIGHT,
    MOUSE_LEFT;


}
